### ISSUE TITLE
Login not possible?

### ISSUE THREAD

**Issue by Achim63** [stanographer/aloft#1]
Hi Stan,
I was following your instructions and have aloft running locally. But I cannot login as a captioner, so how do I create a new (admin) user?
For now I can use the demo part, but there I have another problem: saving the session as .txt from the menu, it seems to work, but I can't find the file anywhere on my Mac, so I'd like to know where those files end up.

Thanks a lot for your work so far!

**Comment by stanographer** [comment]
Ooh sorry! Try navigating to localhost/users/new!

**Comment by Achim63** [comment]
Thank you, I was able to create a new "event" after creating a new user. There was an error when I clicked on "log in with new user" (or some such) after creation, but I could log in coming from the start page.
I'm far from realtime speed, but I hope using this I can use my Cybra with an attached little Windows tablet and while writing see the result on my big iMac screen as well. So I can build a wireless steno machine with its own "display" over Wi-Fi.
Now I just have to find out how to tweak the path to the saved .txt files.

**Comment by Achim63** [comment]
I just reproduced said error message by trying to go to localhost/users/, maybe the output can help you debugging it:

```
ReferenceError: /Users/Achim/aloft/ver-1.7/views/events/byauthor.ejs:19
   17|     <div id="navbar" class="collapse navbar-collapse">
   18|       <ul class="nav navbar-nav navbar-right">
>> 19|         <li class="active"><a href="./<%= currentUser %>">Events by <%= firstname %> <%= lastname %><span class="sr-only">(current)</span></a></li>
   20|         <li><a href="/events">All Events</a></li>
   21|         <li><a href="/users/logout">Logout</a></li>
   22|          </ul>

currentUser is not defined
   at eval (eval at <anonymous> (/Users/Achim/aloft/ver-1.7/node_modules/ejs/lib/ejs.js:485:12), <anonymous>:12:23)
   at returnedFn (/Users/Achim/aloft/ver-1.7/node_modules/ejs/lib/ejs.js:514:17)
   at View.exports.renderFile [as engine] (/Users/Achim/aloft/ver-1.7/node_modules/ejs/lib/ejs.js:358:31)
   at View.render (/Users/Achim/aloft/ver-1.7/node_modules/express/lib/view.js:126:8)
   at tryRender (/Users/Achim/aloft/ver-1.7/node_modules/express/lib/application.js:639:10)
   at EventEmitter.render (/Users/Achim/aloft/ver-1.7/node_modules/express/lib/application.js:591:3)
   at ServerResponse.render (/Users/Achim/aloft/ver-1.7/node_modules/express/lib/response.js:961:7)
   at ServerResponse.res.render (/Users/Achim/aloft/ver-1.7/node_modules/express-ejs-layouts/lib/express-layouts.js:68:12)
   at Query.<anonymous> (/Users/Achim/aloft/ver-1.7/index.js:98:11)
   at /Users/Achim/aloft/ver-1.7/node_modules/mongoose/node_modules/kareem/index.js:177:19
   at /Users/Achim/aloft/ver-1.7/node_modules/mongoose/node_modules/kareem/index.js:109:16
   at nextTickCallbackWith0Args (node.js:415:9)
   at process._tickCallback (node.js:344:13)
```

**Comment by stanographer** [comment]
Oh interesting. I've never seen that before. I'm currently on a subway home but I'll check it out as soon as I can get on my laptop.

**Comment by Achim63** [comment]
I get that error each time I try to log in. Then I have to go back to the start page and click on "Begin as captioner" again - and as that opens the Event page, apparently login was successful.
So it's at least easy to work around.

**Comment by Achim63** [comment]
On the Windows tablet I couldn't log in at all with v1.7 (server running on my iMac). Now I switched to 1.7-m and it works as expected.

**Comment by stanographer** [comment]
Sorry I kinda fell off the earth! I'm dealing with a move right now so my responses are gonna be slow. Maybe try 1.8 now?

**Comment by stanographer** [comment]
"currentUser is not defined" means that there is no session data that express sessions is reading from. You logged in with localhost/users/login, right?

**Comment by Achim63** [comment]
Oh, you're living on a pink cloud now? ;-)
As mentioned above, login works fine in 1.7.-m. I'll try 1.8 and let you know of any issues I might encounter.
